sudo : required
services:
 - docker
before_install:
  - docker build -t srinivasaleti/frontend -f ./simple-react/Dockerfile ./simple-react
script:
  - echo Finished
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-Frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-157078391004"
  bucket_path: "Docker-Frontend"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_KEY"