version: '3.2'

services:
  back-end:
    container_name: back-end
    build: 
      context: backend/
      dockerfile: Dockerfile
    ports: 
      - '5000:5000'
  front-end:
    container_name: front-end
    build: 
      context: simple-react/
      dockerfile: Dockerfile.prod
    ports: 
      - '8080:80'
    depends_on: 
      - back-end