FROM node:12.2.0-alpine as build
WORKDIR /usr/src

COPY package.json .
RUN npm install

COPY . .
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /usr/src/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]